'use strict';

/**
 * The default alphabet consists of alphanumeric characters.
 * Any numbers that look like letters and vice versa are removed:
 * 1 l, 0 o.
 * Also the following letters are not present, to prevent any
 * expletives: cfhistu
 */
const ALPHABET = '23456789ABDEGJKMNPQRVWXYZabdegjkmnpqrvwxyz';
const ALPHABET_LENGTH = ALPHABET.length;

const HashID = {};

/**
 * Returns a randomly-generated friendly ID.
 * Note that the friendly ID is not guaranteed to be
 * unique to any other ID generated by this same method,
 * so it is up to you to check for uniqueness.
 * @return {String} friendly ID.
 */
HashID.generate = function(length) {
  var rtn = '';
  for (var i = 0; i < length; i++) {
    rtn += ALPHABET.charAt(Math.floor(Math.random() * ALPHABET_LENGTH));
  }
  return rtn;
};

module.exports = HashID;
